src/Entity/Todo.php
<?php

namespace App\Entity;

use App\Repository\TodoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TodoRepository::class)
 */
class Todo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $priority;

    /**
     * @ORM\Column(type="datetime")
     */
    private $due_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_due;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPriority(): ?string
    {
        return $this->priority;
    }

    public function setPriority(string $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getDueDate(): ?\DateTimeInterface
    {
        return $this->due_date;
    }

    public function setDueDate(\DateTimeInterface $due_date): self
    {
        $this->due_date = $due_date;

        return $this;
    }

    public function getCreateDue(): ?\DateTimeInterface
    {
        return $this->create_due;
    }

    public function setCreateDue(\DateTimeInterface $create_due): self
    {
        $this->create_due = $create_due;

        return $this;
    }
}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

use App\Entity\Todo;

class TodoController extends AbstractController
{
    /**
     * @Route("/", name="todo")
     */
    public function index(): Response
    {
        $todos = $this->getDoctrine()->getRepository(Todo::class)->findAll();       /** other way: (App:todo) **/ 
        // dd($todos);
        return $this->render('todo/index.html.twig', [
           'todos' => $todos 
        ]);
    }

    /**
     * @Route("/create", name="create_todo")
     */
    public function create(Request $request): Response
    {
        $todo = new Todo;
        $form = $this->createFormBuilder($todo)->add("name", TextType::class, array('attr'=>array("class"=>"form-control fw-light border-1 border-muted rounded-pill bg-light shadow-sm mt-3 text-muted", "style"=>"margin-bottom:15px")))
        ->add("category", TextType::class, array('attr'=>array("class"=>"form-control fw-light border-1 border-muted rounded-pill bg-light shadow-sm mt-3 text-muted", "style"=>"margin-bottom:15px")))
        ->add("description", TextareaType::class, array('attr'=>array("class"=>"form-control fw-light border-1 border-muted rounded bg-light shadow-sm mt-3 text-muted", "style"=>"margin-bottom:15px")))
        ->add("priority", ChoiceType::class, array('attr'=>array("class"=>"form-control fw-light border-1 border-muted rounded-pill bg-light shadow-sm mt-3 text-muted", "style"=>"margin-bottom:15px"), "choices"=> array('Low'=>'Low', 'Normal'=>'Normal', 'High'=>'High')))
        ->add("due_date", DateTimeType::class, array('attr'=>array("class"=>"form-control fw-light border-1 border-muted rounded bg-light shadow-sm mt-3 text-muted p-3", "style"=>"margin-bottom:15px")))
        ->add("save", SubmitType::class, array('attr'=>array("class"=>"btn-outline-primary fw-light btn-sm border-1 shadow-sm rounded-pill m-3", "style"=>"margin-bottom:15px"),"label"=>"create todo"))->getForm();
        // ->add('save', SubmitType::class, array('label'=> 'Create Todo', 'attr' => array('class'=> 'btn-primary', 'style'=>'margin-bottom:15px')))->getForm();
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $name = $form["name"]->getData();
            $category = $form["category"]->getData();
            $description = $form["description"]->getData();
            $priority =$form["priority"]->getData();

            $due_date =$form["due_date"]->getData();

            $now = new \DateTime('now');

            $todo->setName($name);
            $todo->setCategory($category);
            $todo->setDescription($description);
            $todo->setPriority($priority);
            $todo->setDueDate($due_date);
            $todo->setCreateDue($now);

            $em = $this->getDoctrine()->getManager();

            $em->persist($todo);
            $em->flush();

            $this->addFlash('notice', 'Todo Added');

            return $this->redirectToRoute('todo');
        }

        return $this->render('todo/create.html.twig', [  
            "form" => $form->createView()
         ]);
    }

    /**
     * @Route("/details/{id}", name="details_todo")
     * 
     */
    public function details($id): Response
    {
        $todo = $this->getDoctrine()->getRepository('App:Todo')->find($id);
        return $this->render('todo/details.html.twig', [
            "todo" => $todo
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit_todo")
     */
    public function edit($id, Request $request): Response
    {
        $todo = $this->getDoctrine()->getRepository(Todo::class)->find($id);
        $form = $this->createFormBuilder($todo)
        ->add("name", TextType::class, array('attr'=>array("class"=>"form-control fw-light border-1 border-muted rounded-pill bg-light shadow-sm mt-3 text-muted", "style"=>"margin-bottom:15px")))
        ->add("category", TextType::class, array('attr'=>array("class"=>"form-control fw-light border-1 border-muted rounded-pill bg-light shadow-sm mt-3 text-muted", "style"=>"margin-bottom:15px")))
        ->add("description", TextareaType::class, array('attr'=>array("class"=>"form-control fw-light border-1 border-muted rounded bg-light shadow-sm mt-3 text-muted", "style"=>"margin-bottom:15px")))
        ->add("priority", ChoiceType::class, array('attr'=>array("class"=>"form-control fw-light border-1 border-muted rounded-pill bg-light shadow-sm mt-3 text-muted", "style"=>"margin-bottom:15px"), "choices"=> array('Low'=>'Low', 'Normal'=>'Normal', 'High'=>'High')))
        ->add("due_date", DateTimeType::class, array('attr'=>array("class"=>"form-control fw-light border-1 border-muted rounded bg-light shadow-sm mt-3 text-muted p-3", "style"=>"margin-bottom:15px ")))
        ->add("save", SubmitType::class, array('attr'=>array("class"=>"btn-outline-primary fw-light btn-sm border-1 shadow-sm rounded-pill m-3", "style"=>"margin-bottom:15px; "),"label"=>"edit todo"))->getForm();
        // ->add('save', SubmitType::class, array('label'=> 'Create Todo', 'attr' => array('class'=> 'btn-primary', 'style'=>'margin-bottom:15px')))->getForm();
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $name = $form["name"]->getData();
            $category = $form["category"]->getData();
            $description = $form["description"]->getData();
            $priority =$form["priority"]->getData();

            $due_date =$form["due_date"]->getData();

            $now = new \DateTime('now');

            $todo->setName($name);
            $todo->setCategory($category);
            $todo->setDescription($description);
            $todo->setPriority($priority);
            $todo->setDueDate($due_date);
            $todo->setCreateDue($now);

            $em = $this->getDoctrine()->getManager();

            $em->persist($todo);
            $em->flush();

            $this->addFlash('notice', 'Todo Edited');

            return $this->redirectToRoute('todo');
        }
        
        return $this->render('todo/edit.html.twig', [  
            "form" => $form->createView()
         ]);
    }

    /**
     * @Route("/delete/{id}", name="delete_todo")
     * 
     */
    public function delete($id): Response
    {   $em = $this->getDoctrine()->getManager();
        $todo = $em->getRepository('App:Todo')->find($id);
        // dd($todo);
        $em->remove($todo);
        $em->flush();

        $this->addFlash('notice', 'Todo Removed');

        return $this->redirectToRoute('todo');
    }

    
}

templates/todo/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create{% endblock %}

{% block body %}

   <h2 class="page-header fw-light text-center py-5 test"> Add Todo </h2>
    <div class="container ">
        <div class="row d-flex justify-content-center" >
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 ">
                <div class="form border-4 mb-4">
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/todo/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details{% endblock %}

{% block body %}
<div class="d-flex justify-content-center  mt-5 ">
    <div class="card bg-light " >
        <div class="card-body shadow" style="width:18rem;">
            <h5 class="card-title">{{ todo.name }}</h5>
            <p class="card-text">{{todo.dueDate | date('F j, Y, g:i a')}}<br>
            {{ todo.category }}<br>
            {{ todo.priority }}<br>
            {{ todo.description }}
            </p>
            <a href="/edit/{{ todo.id }}" class="btn btn-outline-success btn-sm fw-light rounded-pill">edit</a>
            <a href="/delete/{{ todo.id }}" class="btn btn-outline-danger btn-sm fw-light rounded-pill">delete</a>  
        </div>
    </div>
</div>
{% endblock %}

templates/todo/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details{% endblock %}

{% block body %}
    <h2 class="page-header fw-light text-center py-5"> Edit Todo </h2>
    <div class="container ">
        <div class="row d-flex justify-content-center" >
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 ">
                <div class="form mb-4">
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/todo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TodoController!{% endblock %}

{% block body %}
<div class="container mt-5">
     <h2 class="text-center mt-2 mb-5 fw-light"> Latest Todos</h2>
   
    <div class="row">
        {% for todo in todos %}
            <div class="col-10 offset-1 col-md-4 offset-md-0">
                <div class="card mb-4" >
                    <div class="card-body shadow bg-light">
                        <h5 class="card-title">{{ todo.name }}</h5>
                        <p class="card-text">{{todo.dueDate | date('F j, Y, g:i a')}}</p>
                        <a href="/edit/{{ todo.id }}" class="btn btn-outline-success btn-sm fw-light rounded-pill">edit</a>
                        <a href="/details/{{ todo.id }}" class="btn btn-outline-warning btn-sm fw-light rounded-pill">details</a>
                        <a href="/delete/{{ todo.id }}" class="btn btn-outline-danger btn-sm fw-light rounded-pill">delete</a>  
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
<div>

{% endblock %}